### ISSUE TITLE
xshell+ssh+zsh+tmux+vim

### ISSUE THREAD

**Issue by tracyone** [icymind/NeoSolarized#10]
My vim setting:(vim 8.0 )

```vim
" some color scheme....

Plug 'sjl/badwolf'
Plug 'iCyMind/NeoSolarized'
Plug 'cocopon/iceberg.vim'
Plug 'tomasr/molokai'
Plug 'morhetz/gruvbox'
Plug 'NLKNguyen/papercolor-theme'
Plug 'KabbAmine/yowish.vim'

" .....

let g:neosolarized_bold = 1
let g:neosolarized_underline = 1
let g:neosolarized_italic = 0
set background=dark
if (has("termguicolors"))
    set termguicolors
endif
```

My zsh setting:(zsh 5.2)

```bash
# run tmux
which tmux > /dev/null
if [[ $? -eq 0  ]]; then
	case $- in *i*)
		[ -z "$TMUX" ] && exec $(tmux -2)
	esac
fi
export TERM=xterm-256color
```

My tmux setting:(tmux 2.4)

```conf
set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "screen-256color"
```

 NeoSolarized's color is not correct while papercolor-theme is correct.

**Comment by icymind** [comment]
sorry I'm not sure whether Xshell support truecolor or not.
The papercolor-theme is a 256 color theme, so it works well. 
You should try the original [solarized](https://github.com/altercation/solarized), it's a 256 color theme.

**Comment by tracyone** [comment]
@icymind 

![screenshot](https://camo.githubusercontent.com/0fe9bd86d014f888d26b0aeda02e153df3fc5ce6/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313135383735342f3635313834392f38303137663666632d643438342d313165322d386164342d3661663932643336323764342e706e67)
