### ISSUE TITLE
gitgutter support?

### ISSUE THREAD

**Issue by tpict** [icymind/NeoSolarized#12]
The first screenshot in the readme shows the gitgutter add sign using the Solarized green colour, but when I load the colourscheme it's using the gitgutter built-in green. I don't see any of the gitgutter highlight groups in `NeoSolarized.vim`

**Comment by icymind** [comment]
gitgutter would override "sign colum" color by default.
You can disable this by config your init.vim:

```vim
let g:gitgutter_override_sign_column_highlight = 0
```

**Comment by tpict** [comment]
I do use that setting - the problem isn't with the sign column highlighting, it's that the symbol characters don't use the Solarized palette. For example, the add symbol is `#009900` where it should be `#5f8700`.

I use

```vim
hi! link GitGutterAdd DiffAdd
hi! link GitGutterChange DiffChange
hi! link GitGutterDelete DiffDelete
hi! link GitGutterChangeDelete DiffChange
```

**Comment by icymind** [comment]
sorry for the delay reply.
I found the gitgutter color was defined in my vimrc, now I add to the theme. Please update to latest version
