### ISSUE TITLE
Backticks disappear in markdown files

### ISSUE THREAD

**Issue by ameyer-pivotal** [icymind/NeoSolarized#18]
Backticks seem to disappear when editing markdown files. They reappear when you are inside them or on the line that contains them. See screenshots.

<img width="167" alt="screen shot 2018-10-31 at 11 11 34 am" src="https://user-images.githubusercontent.com/24568368/47802381-224bd880-dcfe-11e8-9011-fdf224d93b4b.png">
<img width="185" alt="screen shot 2018-10-31 at 11 11 54 am" src="https://user-images.githubusercontent.com/24568368/47802382-224bd880-dcfe-11e8-8b16-9f1b87fa1ed5.png">
<img width="249" alt="screen shot 2018-10-31 at 11 12 08 am" src="https://user-images.githubusercontent.com/24568368/47802383-224bd880-dcfe-11e8-84d4-4be227646ba8.png">

Thanks for the help with this!

**Comment by malob** [comment]
I suspect this isn't a problem with the colorscheme and that you have a `conceallevel` set.

Do the backticks still disappears if you run `:set conceallevel=0`

**Comment by ameyer-pivotal** [comment]
@malob Yep, that did it! Thanks. Closing.
