### ISSUE TITLE
urxvt issue

### ISSUE THREAD

**Issue by NeoTheFox** [iCyMind/NeoSolarized#2]
I have an issue with this and urxvt - the background is messed up.
Colour support: ![screenshot](http://i.imgur.com/lMfdgve.png)
How it looks in nvim: ![screenshot](http://i.imgur.com/bm0zCGU.png)
init.vm: http://i.imgur.com/bm0zCGU.png

It works fine with nvim-qt.

**Comment by iCyMind** [comment]
If your terminal support true color, the colors will smoothly blend like this:
![screen shot 2016-10-06 at 4 59 18 pm](https://cloud.githubusercontent.com/assets/1908329/19146536/84026faa-8be6-11e6-87a3-393bbfc5570e.png)

Please update your urxvt.

**Comment by NeoTheFox** [comment]
Whoops, I've done goofed. Sorry for bothering.

**Comment by Vonfry** [comment]
I have the same problem. I use only urxvt without any other terminal emulators. After system start, run lightdm and xmonad. And open urxvt in xmonad.
