### ISSUE TITLE
vim-airline uses default colors

### ISSUE THREAD

**Issue by ssipos90** [iCyMind/NeoSolarized#30]
Hi,

I installed this theme and all works great, but vim-airline doesn't switch.
I have neovim 0.5 and minpac.

```
set background=light
set termguicolors
colorscheme NeoSolarized
```

Any help would be appreciated.
Thanks

**Comment by jhscheer** [comment]
You could try:

> To use solarized dark, set `:AirlineTheme solarized` and add the following to your .vimrc: `let g:airline_solarized_bg='dark'`

However, this seems like a question for [vim-airline](https://github.com/vim-airline).

**Comment by ssipos90** [comment]
@jhscheer thanks!

I've since discovered that vim-airline has different theming and you need to add yet another package for those extras.
I'm gonna close this
