### ISSUE TITLE
Gutter highlights

### ISSUE THREAD

**Issue by BonarBeavis** [icymind/NeoSolarized#5]
Hi,

Neomake and git-gutter signs have different backgrounds:

![image](https://cloud.githubusercontent.com/assets/3330855/20084331/e1323f7c-a561-11e6-9a56-ced6e9d4722c.png)

Got no signature signs installed.

Cheers

**Comment by BonarBeavis** [comment]
Fix: 

let g:gitgutter_override_sign_column_highlight = 0

**Comment by icymind** [comment]
Thanks. Maybe I should write it to the readme
