### ISSUE TITLE
How to remove this in vim

### ISSUE THREAD

**Issue by tracyone** [icymind/NeoSolarized#9]
<img width="525" alt="2017-01-27 7 05 07" src="https://cloud.githubusercontent.com/assets/4246425/22368823/8b34aafa-e4c3-11e6-93d2-35aff941a285.png">

in neovim

<img width="555" alt="2017-01-27 7 06 40" src="https://cloud.githubusercontent.com/assets/4246425/22368878/cb273a88-e4c3-11e6-97ad-dcbb30f34cec.png">

**Comment by icymind** [comment]
You see this because vim will render italic text as reverse format(I don't know why😂😂). 

I have fixed this by disable italic text. Update to latest version pls.
